version: '2'

services:
  pdi-slave:
    build: .
    image: zhicwu/pdi-ce${PDI_IMAGE_TAG}
    hostname: ${SERVER_HOST}
    container_name: ${PDI_CONTAINER_NAME}
    command: slave
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "12345:12345"
    volumes:
      - ./ext:/pdi-ext:ro
      - ./data/logs:/data-integration/logs:rw
      - ./data/cache:/data-integration/system/karaf/caches:rw
      - ./data/data:/data-integration/system/karaf/data:rw
      - ./data/tmp:/tmp:rw
    environment:
      # uncomment below if you want to see the generated admin password
      #DEBUG: Y
      PENTAHO_DI_JAVA_OPTIONS: '${PENTAHO_DI_JAVA_OPTIONS}'
      HOST_USER_ID: ${HOST_USER_ID}
      PDI_HADOOP_CONFIG: ${PDI_HADOOP_CONFIG}
      PDI_MAX_LOG_LINES: ${PDI_MAX_LOG_LINES}
      PDI_MAX_LOG_TIMEOUT: ${PDI_MAX_LOG_TIMEOUT}
      PDI_MAX_OBJ_TIMEOUT: ${PDI_MAX_OBJ_TIMEOUT}
      CERT_COUNTRY: ${CERT_COUNTRY}
      CERT_STATE: ${CERT_STATE}
      CERT_LOCATION: ${CERT_LOCATION}
      CERT_ORGANIZATION: ${CERT_ORGANIZATION}
      CERT_ORG_UNIT: ${CERT_ORG_UNIT}
      CERT_NAME: ${CERT_NAME}
      SERVER_NAME: ${SERVER_NAME}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_USER: ${SERVER_USER}
      SERVER_PASSWD: ${SERVER_PASSWD}
      MASTER_NAME: ${MASTER_NAME}
      MASTER_HOST: ${MASTER_HOST}
      MASTER_PORT: ${MASTER_PORT}
      MASTER_CONTEXT: ${MASTER_CONTEXT}
      MASTER_USER: ${MASTER_USER}
      MASTER_PASSWD: ${MASTER_PASSWD}
    # still need below even using docker engine 1.12
    # see more at https://github.com/docker/docker/issues/21051 and https://docs.docker.com/engine/security/seccomp/
    security_opt:
      - seccomp:unconfined
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    restart: always
    network_mode: bridge
    external_links:
    - postgreststarterkit_db_1:db
    - sftp_sftp_1:sftp

  nginx: 
    image: nginx:latest
    links:
      - pdi-slave:pdi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: bridge
    restart: always
    ports:
      - "9090:9090"